"use client";
import { useEffect, useState } from "react";
import Shell from "../../components/Shell";
import { apiGet, apiPost, getStoredChannelId } from "../../lib/api";

type Project={id:string;topic:string;status:string};
type Analysis={id:string;project_id:string;status:string;score:number;sampled_frames:number;issues:string[];recommendations:string[];reedit_plan:{scenes?:Array<{scene:number;time_range:number[];reason:string[];actions:string[]}>}};
export default function CreativePage(){
 const [project,setProject]=useState<Project|null>(null); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function load(){const channel=getStoredChannelId(); if(!channel)return; const r=await apiGet<{projects:Project[]}>(`/api/v1/channels/${channel}/projects`); const p=r.projects.find(x=>x.status==="READY_TO_PUBLISH")||r.projects[0]; if(!p)return; setProject(p); const a=await apiGet<{analyses:Analysis[]}>(`/api/v1/creative/projects/${p.id}/analyses`); setAnalysis(a.analyses[0]||null);}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Failed to load creative intelligence"));},[]);
 async function analyze(){if(!project)return; setBusy(true);setError("");try{const r=await apiPost<Analysis>(`/api/v1/creative/projects/${project.id}/analyze`,{});setAnalysis(r);}catch(e){setError(e instanceof Error?e.message:"Analysis failed")}finally{setBusy(false)}}
 async function reedit(){if(!project||!analysis)return;setBusy(true);setError("");try{await apiPost(`/api/v1/creative/projects/${project.id}/reedit`,{analysis_id:analysis.id});await load()}catch(e){setError(e instanceof Error?e.message:"Re-edit failed")}finally{setBusy(false)}}
 return <Shell><div className="topbar"><div><div className="kicker">Creative Intelligence</div><h1>Video Understanding</h1><p className="sub">Scene-level visual, audio and narration alignment analysis.</p></div></div>{error&&<div className="error">{error}</div>} {!project?<div className="panel empty">No project found.</div>:<><div className="panel"><div className="cardTitle"><div><div className="kicker">Project</div><h2>{project.topic}</h2></div><span className="badge">{project.status}</span></div><div className="actions"><button className="btn primary" disabled={busy} onClick={()=>void analyze()}>{busy?"Analyzing…":"Analyze video"}</button>{analysis?.reedit_plan?.scenes?.length?<button className="btn" disabled={busy} onClick={()=>void reedit()}>Create targeted re-edit</button>:null}</div></div>{analysis&&<div className="grid grid3"><div className="panel"><div className="kicker">Creative score</div><div className="metric">{analysis.score}</div><div className="mini">{analysis.sampled_frames} sampled frames</div></div><div className="panel"><div className="kicker">Status</div><div className="metric">{analysis.status}</div></div><div className="panel"><div className="kicker">Scenes to re-edit</div><div className="metric">{analysis.reedit_plan?.scenes?.length||0}</div></div></div>}{analysis?.reedit_plan?.scenes?.map(s=><div className="panel" key={s.scene}><div className="cardTitle"><h2>Scene {s.scene}</h2><span className="badge">{s.time_range?.[0]}–{s.time_range?.[1]}s</span></div><div className="mini">{s.reason?.join(" · ")}</div><div className="mini" style={{marginTop:8}}>{s.actions?.join(" · ")}</div></div>)}</>}</Shell>
}
