"use client";
import { useState } from "react";
import { apiGet, apiPost } from "@/lib/api";

export default function PlannerPage(){
 const [channelId,setChannelId]=useState(""); const [goal,setGoal]=useState(""); const [budget,setBudget]=useState("0"); const [plan,setPlan]=useState<any>(null); const [error,setError]=useState("");
 async function create(){ setError(""); try { const p=await apiPost<any>(`/api/v1/planner/channels/${channelId}/plans`,{goal,budget_usd:Number(budget),context:{}}); setPlan(await apiGet<any>(`/api/v1/planner/plans/${p.id}`)); } catch(e:any){setError(e?.message||"Unable to create plan")} }
 async function refresh(){ if(plan?.plan?.id)setPlan(await apiGet<any>(`/api/v1/planner/plans/${plan.plan.id}`)); }
 async function materialize(){ if(!plan?.plan?.id)return; await apiPost(`/api/v1/planner/plans/${plan.plan.id}/materialize`,{}); await refresh(); }
 return <main className="space-y-6"><div><h1 className="text-2xl font-semibold">Agent Planner & Dynamic Workflow Graph</h1><p className="text-sm text-slate-500">Goal decomposition, capability matching, budget-aware planning, governance admission and replanning.</p></div>
 <section className="rounded-xl border p-4 grid gap-3"><input className="rounded border px-3 py-2" value={channelId} onChange={e=>setChannelId(e.target.value)} placeholder="Channel UUID"/><input className="rounded border px-3 py-2" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Goal, e.g. produce a high-retention technology video"/><input className="rounded border px-3 py-2" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Budget USD"/><button className="rounded bg-black px-4 py-2 text-white" onClick={()=>void create()}>Build plan</button>{error&&<div className="text-sm text-red-600">{error}</div>}</section>
 {plan&&<section className="space-y-3"><div className="rounded-xl border p-4"><div className="flex justify-between"><div><h2 className="font-semibold">{plan.plan.goal}</h2><div className="text-sm text-slate-500">Status {plan.plan.status} · v{plan.plan.plan_version} · ${Number(plan.plan.estimated_cost_usd).toFixed(2)} estimated · confidence {Math.round(Number(plan.plan.confidence)*100)}%</div></div><div className="flex gap-2"><button className="rounded border px-3 py-1" onClick={()=>void refresh()}>Refresh</button><button className="rounded bg-black px-3 py-1 text-white" onClick={()=>void materialize()}>Materialize ready</button></div></div><div className="mt-3 text-xs text-slate-500">{plan.plan.rationale?.join(" ")}</div></div>
 <div className="grid gap-3 md:grid-cols-2">{plan.nodes.map((n:any)=><div key={n.id} className="rounded-xl border p-4"><div className="flex justify-between"><span className="font-medium">{n.node_key}</span><span className="rounded-full border px-2 py-1 text-xs">{n.status}</span></div><div className="mt-2 text-sm">{n.agent_key} · {n.task_type}</div><div className="text-xs text-slate-500">Capability {n.requested_capability} · action {n.action_type}</div><div className="text-xs text-slate-500">Cost ${Number(n.estimated_cost_usd).toFixed(2)} · confidence {Math.round(Number(n.confidence)*100)}% · governance {n.governance_mode}</div><div className="mt-2 text-xs">{n.rationale}</div></div>)}</div></section>}
 </main>
}
