"use client";

import { useEffect, useState } from "react";
import Shell from "../../components/Shell";
import { apiGet } from "../../lib/api";

type Profile={id:string;provider:string;service:string;kind:string;quality_tier:string;priority:number;unit:string;unit_cost_usd:number;enabled:boolean;capabilities:Record<string,unknown>;config:Record<string,unknown>};
type Decision={id:string;step_name:string;service:string;requested_tier:string;chosen_provider:string;chosen_tier:string;fallback_used:boolean;estimated_cost_usd:number;reason:string;created_at:string};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:4}).format(n);
export default function RoutingPage(){
  const [profiles,setProfiles]=useState<Profile[]>([]); const [decisions,setDecisions]=useState<Decision[]>([]); const [error,setError]=useState("");
  useEffect(()=>{void Promise.all([apiGet<{profiles:Profile[]}>("/api/v1/routing/providers"),apiGet<{decisions:Decision[]}>("/api/v1/routing/decisions?limit=50")]).then(([p,d])=>{setProfiles(p.profiles);setDecisions(d.decisions)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load routing"));},[]);
  return <Shell><div className="topbar"><div><div className="kicker">Cost-aware orchestration</div><h1>Provider Routing</h1><p className="sub">Inspect provider capabilities, economics, fallback paths and the audit trail generated by workflows.</p></div></div>{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}<div className="grid grid2"><div className="panel"><div className="cardTitle"><h2>Configured providers</h2><span className="badge success">{profiles.length}</span></div>{profiles.length===0?<div className="empty">No custom profiles. Built-in defaults are selected from environment settings.</div>:profiles.map(p=><div className="idea" key={p.id}><div className="ideaText"><strong>{p.provider}</strong><small>{p.service} · {p.kind} · {p.quality_tier} · {money(p.unit_cost_usd)}/{p.unit}</small></div><span className={`badge ${p.enabled?"success":""}`}>{p.enabled?"Enabled":"Disabled"}</span></div>)}</div><div className="panel"><div className="cardTitle"><h2>Fallback decisions</h2><span className="badge">{decisions.filter(d=>d.fallback_used).length}</span></div>{decisions.length===0?<div className="empty">No decisions yet.</div>:decisions.map(d=><div className="idea" key={d.id}><div className="ideaText"><strong>{d.step_name} → {d.chosen_provider}</strong><small>{d.reason}</small></div><span className={`badge ${d.fallback_used?"warn":"success"}`}>{d.fallback_used?"Fallback":"Primary"}</span></div>)}</div></div></Shell>;
}
